version: "3.7"

services:
  redis:
    image: docker.io/library/redis:alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server --save 30 1 --loglevel warning
    volumes:
      - redis-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    image: searxng-dev:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:7070:8080"
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    environment:
      - LIMITER=true
      - REDIS_URL=redis://redis:6379/0
      - PRIVACYPOLICY=https://priv.au/privacy/
      - IMAGE_PROXY=true
      - CONTACT=https://vojk.au/
      - SEARCH_DEFAULT_LANG=en-US
      - SEARCH_ENGINE_ACCESS_DENIED=60
      - PUBLIC_INSTANCE=true

volumes:
  redis-data:

