[real_ip]

# Number of values to trust for X-Forwarded-For.
x_for = 1

# The prefix defines the number of leading bits in an address that are compared
# to determine whether or not an address is part of a (client) network.

# I don't think I will have any issues blocking the entire /24. 
ipv4_prefix = 24

# /40s of IPv6 can be rented for under a dollar / month. It makes logical sense to limit the entire /40 prefix.
ipv6_prefix = 40

[botdetection.ip_limit]

# To get unlimited access in a local network, by default link-lokal addresses
# (networks) are not monitored by the ip_limit
filter_link_local = false

# activate link_token method in the ip_limit method
link_token = true

[botdetection.ip_lists]

# In the limiter, the ip_lists method has priority over all other methods -> if
# an IP is in the pass_ip list, it has unrestricted access and it is also not
# checked if e.g. the "user agent" suggests a bot (e.g. curl).

pass_ip = [
  '2001:19f0:4400:459f:71b9:9532:fb2d:9d65/64',
  '66.42.52.144/32'      # Allow my own private server to query. For things like testing TLS and setting up searx.space locally without being limited.
  # '192.168.0.0/16',      # IPv4 private network
  # 'fe80::/10'            # IPv6 linklocal / wins over botdetection.ip_limit.filter_link_local
]

# Activate passlist of (hardcoded) IPs from the SearXNG organization,
# e.g. `check.searx.space`.
pass_searxng_org = true
