name: build

on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t test-image .

      - name: Run Docker container
        run: docker run -d -p 8080:8080 test-image

      - name: Test /healthz endpoint
        run: |
          sleep 10
          curl http://localhost:8080/healthz | grep "OK"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          ref: base

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildbasex
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: docker_buildbase
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/386
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/searxng:base

      - name: Check Out Main Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildmainx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: docker_buildmain
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/386
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/searxng:production

      - name: Image digest
        run: echo ${{ steps.docker_buildmain.outputs.digest }}
