name: build

on:
  schedule:
    - cron: '5 * * * *'
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - 'src/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    #- name: Update the SHA sum.
    #  run: |
    #    git ls-remote https://github.com/searxng/searxng |  head -1 | cut -f 1 | sed -e "s/.*/UPSTREAM_COMMIT=&/" | sed -i '8r/dev/stdin' Dockerfile && sed -i '8d' ./Dockerfile
        
    - name: Push changes
      uses: actions-js/push@master
      with:
        author_name: 'github-actions[bot'
        author_email: '41898282+github-actions[bot]@users.noreply.github.com'
        message: '[feat] Update SearXNG to Latest'
        github_token: ${{ secrets.PAT_TOKEN }}

    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
        ref: base

    #- name: Copy requirements.txt
    #  run: |
    #    git checkout base
    #    curl https://raw.githubusercontent.com/searxng/searxng/master/requirements.txt > requirements.txt
        
    - name: Push changes
      uses: actions-js/push@master
      with:
        author_name: 'github-actions[bot'
        author_email: '41898282+github-actions[bot]@users.noreply.github.com'
        message: '[feat] Update requirements.txt to Latest'
        branch: 'base'
        github_token: ${{ secrets.PAT_TOKEN }}

  test:
    needs: update
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t test-image .

      - name: Run Docker container
        run: docker run -d -p 8080:8080 test-image

      - name: Test /healthz endpoint
        run: |
          sleep 10
          curl http://localhost:8080/healthz | grep "OK"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          ref: base

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildbasex
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: docker_buildbase
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/searxng:base

      - name: Check Out Main Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildmainx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: docker_buildmain
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/searxng:production

      - name: Image digest
        run: echo ${{ steps.docker_buildmain.outputs.digest }}
