name: build-main-amd64

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t test-image .

      - name: Run Docker container
        run: docker run -d -p 8080:8080 test-image

      - name: Test /healthz endpoint
        run: |
          sleep 10  # Wait for the container to start
          curl http://localhost:8080/healthz

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/searxng:production

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
