name: ci

on:
  schedule:
    - cron: '5 * * * *'
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - 'src/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

env:
  BASE_TEST_TAG: vojkovic/searxng:base-test
  BASE_PROD_TAG: vojkovic/searxng:base
  BASE_GITHUB_PROD_TAG: ghcr.io/vojkovic/searxng:base
  MAIN_TEST_TAG: vojkovic/searxng:production-test
  MAIN_PROD_TAG: vojkovic/searxng:production
  MAIN_GITHUB_PROD_TAG: ghcr.io/vojkovic/searxng:production

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    #- name: Update the SHA sum.
    #  run: |
    #    git ls-remote https://github.com/searxng/searxng |  head -1 | cut -f 1 | sed -e "s/.*/UPSTREAM_COMMIT=&/" | sed -i '8r/dev/stdin' Dockerfile && sed -i '8d' ./Dockerfile
        
    - name: Push changes
      uses: actions-js/push@master
      with:
        author_name: 'github-actions[bot'
        author_email: '41898282+github-actions[bot]@users.noreply.github.com'
        message: '[feat] Update SearXNG to Latest'
        github_token: ${{ secrets.PAT_TOKEN }}

    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
        ref: base

    #- name: Copy requirements.txt
    #  run: |
    #    git checkout base
    #    curl https://raw.githubusercontent.com/searxng/searxng/master/requirements.txt > requirements.txt
        
    - name: Push changes
      uses: actions-js/push@master
      with:
        author_name: 'github-actions[bot'
        author_email: '41898282+github-actions[bot]@users.noreply.github.com'
        message: '[feat] Update requirements.txt to Latest'
        branch: 'base'
        github_token: ${{ secrets.PAT_TOKEN }}

  build-base:
    needs: update
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          ref: base

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Test Base Image
        uses: docker/build-push-action@v6
        with:
          load: true
          context: ./
          file: ./Dockerfile
          tags: ${{ env.BASE_TEST_TAG }}

      - name: Test Base Image
        run: docker run --rm ${{ env.BASE_TEST_TAG }} /bin/sh -c "echo 'Hello World'"

      - name: Build Production Base Image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.BASE_PROD_TAG }}
            ${{ env.BASE_GITHUB_PROD_TAG }}

  build-main:
    needs: build-base
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Test Main Image
        uses: docker/build-push-action@v6
        with:
          load: true
          context: ./
          file: ./Dockerfile
          tags: ${{ env.MAIN_TEST_TAG }}

      - name: Test Main Image
        run: docker run -d -p 8080:8080 ${{ env.MAIN_TEST_TAG }} && sleep 5 && curl http://localhost:8080/healthz | grep "OK" && docker stop $(docker ps -q --filter ancestor=${{ env.MAIN_TEST_TAG }})

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            - ${{ env.MAIN_PROD_TAG }}
            - ${{ env.MAIN_GITHUB_PROD_TAG }}
